server:
  port: 8080

spring:
  redis:
    host: 43.142.106.101
    port: 6379
    password:
    database: 1
    # 读超时
    timeout: 30000
    # 连接超时
    connectTimeout: 5000
    pool:
      max-active: 20
      max-idle: 5
      max-wait: -1
      min-idle: 0